### ISSUE TITLE
Using QGIS data with Google maps , "geom" column EPSG/SRID 25830...

### ISSUE THREAD

**Issue by scramatte** [mstaack/laravel-postgis#105]
Hi,

I'm trying to integrate your lib with qgis.
I've defined my model with postgistrait , postgis_fields, postgis_types and it works. 
My "geom" column is EPSG/SRID 25830...

```
use Illuminate\Database\Eloquent\Model;
use Phaza\LaravelPostgis\Eloquent\PostgisTrait;
use Phaza\LaravelPostgis\Geometries\Point;

class Cto extends Model
{
        use PostgisTrait;

        protected $connection = 'qgis';
        protected $table = 'markers';

        protected $postgisFields = [ 'geom' ];

        protected $postgisTypes = [
                'geom' => [
                        'geomtype' => 'geography',
                        'srid' => 25830
                ]
        ];    
}
```

When I query  database  my  API returns me the following

```
 "geom": {
      "type": "Point",
      "coordinates": [
        659515.6303383708,
        4209687.836603958
      ]
```

But such coordinates doesn't looks valid to integrate/use with google maps
What I'm doing wrong?

Regards

**Comment by phaza** [comment]
google maps only supports projection 4326, you need to transform your current data into srid 4326.
https://postgis.net/docs/ST_Transform.html

**Comment by scramatte** [comment]
Ok, thank you for the answer.  I'm new with Laravel/Lumen.   
Can you give me some clue  of how can I use such fucntion in the model without make postgre view ?

By the wat,  may it posible to read   SRID 25830  without convert directly with OpenLayers or Leaflet ?

Regards
