### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by njbarrett** [mstaack/laravel-postgis#124]
Hello all,
In my day to day job I am no longer working with Laravel and PostGIS as much so it makes sense to offer the opportunity to continue supporting this repo to someone who does use it regularly.
If you believe you would be a good fit, comment below why and I'll organise a handover.

Cheers.

**Comment by mstaack** [comment]
Would like to help out where i can. Almost started my own package for the geo stuff, until i found this package.
Using Postgres/Postgis and Laravel in my daily job.

**Comment by njbarrett** [comment]
@mstaack sounds good, are you happy for me to transfer the repo to you, and then anyone else who jumps in could be a co-contributor?

**Comment by mstaack** [comment]
sure go ahead, have helped on other laravel db wrappers in the past (like nasty oracle dbs :))

**Comment by Gummibeer** [comment]
@njbarrett out of my experience a package move is a very very very long process. A lot of apps/users won't switch the dependency/namespace and/or whatever have to be changed.
A more common process is to archive and deprecate the current repository and copy/clone/fork it to the new maintainer. This will not throw errors for the ones using `--prefer-source` and so on.

**Comment by njbarrett** [comment]
@Gummibeer thank you for the advice. I went ahead and transferred it because the same was given to me. I originally inherited the repo but kept the original namespace, I will leave it up to the new maintainer/s to decide the best path forwards from here

**Comment by mstaack** [comment]
thankfully i have @Gummibeer in my team ;)
aiming for a laravel 6/7 release only and stabilizing deps/tests
