### ISSUE TITLE
Service provider register issue

### ISSUE THREAD

**Issue by mediclab** [mstaack/laravel-postgis#137]
You can't instantinate your own singletone ConnectionFactory and DatabaseManager classes in 
https://github.com/mstaack/laravel-postgis/blob/a3bb4825245df4997b170a3e01b593909a95db7c/src/DatabaseServiceProvider.php#L36

Because it's can disable all other extensions of connections.
You need to use the` DatabaseManager::extend` class method to add a new ConnectionResolver.

For example: your component may conflicts with `yajra/laravel-oci8` because laravel-oci8 extends default container, which re-instantinate after by your component.

**Comment by spawn-guy** [comment]
the documentation about namespace of that service provider is also not correct. it uses original `Phaza\LaravelPostgis\DatabaseServiceProvider`, but i am on laravel 5.4 😆

**Comment by spawn-guy** [comment]
@mstaack as i see this issue closed, i have a question: was this issue mitigated?
