### ISSUE TITLE
Make release at packagist

### ISSUE THREAD

**Issue by noldors** [mstaack/laravel-postgis#140]
In source code already exist support of Laravel 8, but last release (5.1) does not support Laravel 8 because it require illuminate/database: ^6.0|^7.0
Please upload new release to packagist.

**Comment by Langdi** [comment]
A dependency (`bosnadev/database`) has not yet been updated: https://github.com/bosnadev/database/pull/42. Unfortunately this package doesn't seem very active.

**Comment by mstaack** [comment]
Yeah... basically waiting

**Comment by vodniciarv** [comment]
any changes?

**Comment by stevegrunwell** [comment]
For others watching the thread, [I've detailed a temporary workaround](https://github.com/mstaack/laravel-postgis/issues/142#issuecomment-706765305) while we wait for bosnadev/database#42 to get merged.

**Comment by mstaack** [comment]
fix on peer repo coming soon: https://github.com/bosnadev/database/pull/42

will push new release then, closing this  see #142

**Comment by mstaack** [comment]
now fixed with: https://github.com/mstaack/laravel-postgis/releases/tag/5.2
