### ISSUE TITLE
with this extension how is it possible to create a postgis HSTORE field?

### ISSUE THREAD

**Issue by gianmarxWebmapp** [mstaack/laravel-postgis#147]
I was wondering if this extension is possible to create an HSTORE field (https://www.postgresql.org/docs/current/hstore.html)?

if so how is it possible to create it?

**Comment by mstaack** [comment]
bosnadev contains:
https://github.com/bosnadev/database/blob/master/src/Bosnadev/Database/Schema/Grammars/PostgresGrammar.php#L47
