### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by abrampl** [mstaack/laravel-postgis#165]
Hi, when it will be avilable support for laravel 9 ?

**Comment by ajthinking** [comment]
Im also looking forward to Laravel 9 support.
Until we can have it here, I published a fork: https://github.com/ajthinking/laravel-postgis which seems to work.
Upstream dependency bosnadev also needs bumping, and it somewhat slumbering, so those parts needed is now merged into the above fork repo.

Maintainers, please let me know if I can help add the fork updates in here instead 🙏

**Comment by mstaack** [comment]
l9 released
