### ISSUE TITLE
error when installing for laravel 9

### ISSUE THREAD

**Issue by alireza-salehi** [mstaack/laravel-postgis#169]
composer require mstaack/laravel-postgis

Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bosnadev/database[0.21, ..., 0.21.1] require illuminate/database ^5.0|^6.0|^7.0|^8.0 -> found illuminate/database[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - mstaack/laravel-postgis 5.3 requires bosnadev/database ^0.21 -> satisfiable by bosnadev/database[0.21, 0.21.1].
    - Root composer.json requires mstaack/laravel-postgis ^5.3 -> satisfiable by mstaack/laravel-postgis[5.3].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require mstaack/laravel-postgis:*" to figure out if any version is installable, or "composer require mstaack/laravel-postgis:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by alireza-salehi** [comment]
composer require mstaack/laravel-postgis:*
./composer.json has been updated
Running composer update mstaack/laravel-postgis
h another require.
    - mstaack/laravel-postgis[dev-revert-90-patch-1, dev-add-query-scopes, dev-bugfix/multipoint-one-point, 3.0, ..., 3.6] require illuminate/database ^5.2 -> found illuminate/database[v5.2.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - mstaack/laravel-postgis[4.0, ..., 4.0.1] require illuminate/database ^5.2|^6.0 -> found illuminate/database[v5.2.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - mstaack/laravel-postgis[5.0, ..., 5.1] require illuminate/database ^6.0|^7.0 -> found illuminate/database[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.    - mstaack/laravel-postgis[5.2, ..., 5.2.1] require illuminate/database ^6.0|^7.0|^8.0 -> found illuminate/database[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bosnadev/database[0.21, ..., 0.21.1] require illuminate/database ^5.0|^6.0|^7.0|^8.0 -> found illuminate/database[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires mstaack/laravel-postgis * -> satisfiable by mstaack/laravel-postgis[dev-fix-for-5.1-connection, dev-master, dev-revert-90-patch-1, dev-add-query-scopes, dev-bugfix/multipoint-one-point, 0.1, 0.2, 1.0, 1.1, 1.2, 2.0, ..., 2.19, 3.0, ..., 3.6, 4.0, 4.0.1, 5.0, ..., 5.3, 9999999-dev].

**Comment by mchev** [comment]
https://github.com/mstaack/laravel-postgis/pull/168
