### ISSUE TITLE
Distance, containment, etc. implementations

### ISSUE THREAD

**Issue by chipbell4** [mstaack/laravel-postgis#17]
@phaza, I'd like to implement these for you. However, what structure would you like these to have, and how would like me to lay out tests for those things?

For distance, Euclidean distance fails on the surface of the earth, so you'd probably need something like the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) or better yet, [Vincenty's](https://en.wikipedia.org/wiki/Vincenty's_formulae) which more accurate, but also more computationally expensive. Would the `distance` method live on the `Point` class and take another `Point` though?

For polygon containment, there's plenty of algorithms there, and ray-casting is the fastest I know of (Github folks, correct me). I would think both `Polygon` and `MultiPolygon` would have an implementation that takes a single `Point`.

What are you thoughts?

**Comment by chipbell4** [comment]
Better yet, could we simply integrate with https://github.com/phayes/geoPHP?

**Comment by phaza** [comment]
That's great news!

Geometry::distanceTo(Geometry) would be the abstract idea, with Point to Point being the easiest. Eventually we could include finding the closest points between two geometries(Like Polygon and Linestring), and then calculate the distance between them. But any start is a good start, so just starting with Point to Point would be great. IMO precision is important, so Vincenty's sounds good, but everything is relative. If it makes a request->response cycle too slow/unfeasible, we can't use it.

For containment Polygon and MultiPolygon should check containment against all other Geometries. A Polygon/MultiPolygon can potentially contain another polygon. But again, any start is a good start, so just Polygon::contains(Point) would be awesome.

As for including geoPHP I'm a bit vary. I find the code a bit dirty, and I find code like this a bit weird to say the least: [Collection.class.php#L282-292](https://github.com/phayes/geoPHP/blob/master/lib/geometry/Collection.class.php#L282-292)

It's also not namespaced, nor using autoloading, and generally it looks more academic than PHP if you get what I mean.

**Comment by chipbell4** [comment]
I can certainly agree with geoPHP opinion. One last idea: Since this module is relying on PostGIS support, why not use the built-in database functions to perform this, since it already performs most of the operations you'd want:
```php
    DB::select('select ST_Distance(Point(0, 0), Point(1, 1))');
```

This isn't the prettiest, but I'm pretty sure it'd be faster than any PHP implementation. Perhaps there's a cleaner way to leverage the database for this?

**Comment by phaza** [comment]
Well, of course being able to create distance queries via the DB makes sense, and it needs a prettier interface than today, but if you have two objects, hitting the db for those is a huge penalty. In good optimized apps, hitting the db is always the bottle neck. Now imagine you have 10 objects, and you want to calculate the distance between them all, that's 1000 db calls..

**Comment by phaza** [comment]
I'm 95% sure it will be faster to do the calculation in PHP, but feel free to benchmark it to be sure.
Do 100 iterations with geoPHP, and 100 iterations where you do DB calls like the one you showed, and we'll see.

**Comment by imzeeshan** [comment]
I was able to get Distance and nearby queries working on a geography database. 
```

SELECT id,name,
ST_Distance(ST_GeographyFromText('SRID=4326;POINT($srid_point[1] $srid_point[0])'), location) as distance
FROM places
WHERE ST_DWithin(ST_GeographyFromText('SRID=4326;POINT($srid_point[1] $srid_point[0])'), location, 10000)
```
where $srid_point[1] $srid_point[0] is longitude and latitude values respectively.

**Comment by BrendanTWhite** [comment]
My database is on a whole other server (around 1,000km away from my PHP server!) so for my instance I suspect going out to the server might be slow-ish ... but then again, if someone else is offering to implement it, then I will politely say thankyou and accept it.  :-)

**Comment by chipbell4** [comment]
@BrendanTWhite if you're reasonably "mathy enough", the inverse vincenty algorithm will give you distances all via PHP/Code: https://en.wikipedia.org/wiki/Vincenty%27s_formulae#Inverse_problem

Bear in mind that these do not take into account terrain, and will assume WGS84 (if you use those parameters).

**Comment by veceraj** [comment]
@mstaack by closing this issue, am I to understand that this feature is unwanted?
