### ISSUE TITLE
Unable to install on Laravel 10.15

### ISSUE THREAD

**Issue by sbahr001** [mstaack/laravel-postgis#187]
I am unable to get laravel-postgres to install without warning errors. 

Ran: `composer require mstaack/laravel-postgis:6.1`
Env: 'Laravel Head  php8.2`
Postgres DB 14.3

I have included the output below:
```
The "6.1" constraint for "mstaack/laravel-postgis" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update mstaack/laravel-postgis
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bosnadev/database[0.21, ..., 0.21.1] require illuminate/database ^5.0|^6.0|^7.0|^8.0 -> found illuminate/database[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - mstaack/laravel-postgis 6.1 requires bosnadev/database ^0.21|dev-master -> satisfiable by bosnadev/database[0.21, 0.21.1].
    - Root composer.json requires mstaack/laravel-postgis 6.1 -> satisfiable by mstaack/laravel-postgis[6.1].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Added image for a prettier view:
<img width="1228" alt="Screenshot 2023-07-24 at 9 56 07 PM" src="https://github.com/mstaack/laravel-postgis/assets/1267206/0c1fcd98-3e05-4805-83d4-605a082d15c7">

Thank you ahead of time.

**Comment by ekoilkom** [comment]
i think bosandev/database has been abandoned. please use this https://github.com/BrekiTomasson/database, this repository forked from bosandev/database
https://github.com/bosnadev/database/issues/55

**Comment by mstaack** [comment]
i highly recommend not to use this library in any new projects. consider using magellan package or build your needs function from scratch

**Comment by jeffschuler** [comment]
@mstaack: just confirming... by "this library" you mean your own laravel-postgis, not bosnadev/database, correct?

**Comment by mstaack** [comment]
yes, consider my package archived

**Comment by jeffschuler** [comment]
Thank you
