### ISSUE TITLE
Geometry vs Geography?

### ISSUE THREAD

**Issue by magnolo** [mstaack/laravel-postgis#27]
Thx for your great extension. I just used it to make some migrations and seeding some data to it.

I just ran into an issue where some stuff from the backend wont work and i then realized thats because of  the geom field (multipolygon) which was generated through the migrations wasnt a geometry field. instead an geography field was made. 

Meanwhile i convert the geom field to a geometry in my queries cause of the need of some postgis functions.

So my question here is, how to generate geometry fields for my migration? or am i missing something here?

thx a lot though

**Comment by phaza** [comment]
Hi,
sorry for the late reply, I've avoided work during xmas :)

Currently geometry fields aren't well supported.
I really created this for my own geography needs in a project.

I would love to support geometries though, but currently I don't have time to write new features.
If you want to make a pull request, that would be great.

A few pointers:
To allow geometry fields to be created via migrations, you'll need to add support in these two files:
https://github.com/phaza/laravel-postgis/blob/master/src/Schema/Blueprint.php
https://github.com/phaza/laravel-postgis/blob/master/src/Schema/Grammars/PostgisGrammar.php

maybe add function names like geomPoint and geogPoint. Don't forget to keep backwards compatibility.

To support geometries in models, you'll have to do changes in the files in this folder:
https://github.com/phaza/laravel-postgis/tree/master/src/Eloquent

My suggestion in that $postgisFields is used as an associative array where you declare whether an attribute is geometry or geography:

```PHP
protected $postgisFields = ['location' => Geography::class, 'area' => Geometry::class];
```

Then you can do some switching between ST_GeogFromText and ST_GeomFromText based on that.

**Comment by stevegoddard** [comment]
Hi @phaza and @magnolo ,
I have the same issue. Have either of you made any progress on this? I also need to use a different SRID.
How about doing something like this in the Blueprint.php (rather like when you specify an integer field in a migration):
    /**
     * Add a point column on the table
     *
     * @param      $column
     * @return \Illuminate\Support\Fluent
     */
    public function point($column, $geomtype = 'GEOGRAPHY', $srid = '4326')
    {
        return $this->addColumn('point', $column, compact('geomtype', 'srid'));
    }

Thoughts?
Steve

**Comment by phaza** [comment]
I actually started out like this with srid, but postgis only supports srid
4326 for geographies:
http://postgis.net/docs/manual-1.5/ch04.html#PostGIS_Geography

**Comment by stevegoddard** [comment]
Yes @phaza - I discovered this yesterday! Surely we can trust the users to realise this (or the migration will simply fail. If users want GEOGRAPHY then they can leave the 2 extra parameters blank.

**Comment by stevegoddard** [comment]
The PostGISGrammer.php file would be something like this:

    /**
     * Adds a statement to add a point geometry column
     *
     * @param \Illuminate\Support\Fluent $column
     * @return string
     */
    public function typePoint(Fluent $column)
    {
        // return 'GEOGRAPHY(POINT, 4326)';
        return dd(strtoupper($column->geomtype) . '(POINT, ' . $column->srid . ')');
    }

What do you think @phaza - would you be happy with something like this? I wondered if we should put some validation into the grammer file to check for srid = integer and check if the geomtype is = to either GEOMETRY or GEOGRAPHY??

Steve

**Comment by stevegoddard** [comment]
Ok - this seems to be working well:

    private $allowed_geom_types = ['GEOMETRY', 'GEOGRAPHY'];

    /**
     * Adds a statement to add a point geometry column
     *
     * @param \Illuminate\Support\Fluent $column
     * @return string
     */
    public function typePoint(Fluent $column)
    {
        // return 'GEOGRAPHY(POINT, 4326)';
        if ((in_array(strtoupper($column->geomtype), $this->allowed_geom_types)) && (is_int($column->srid))) {
            return strtoupper($column->geomtype) . '(POINT, ' . $column->srid . ')';
        } else {
            return dd('Error with validation of geom type or srid! (If geom type is GEOGRAPHY then the SRID must be 4326)');
        }
    }

I'll update the rest of the geom types. If you're ok with it i'll fork and put in a pull request.
Need to have a look at the models now - I think it best to do that as a separate pull request?
Steve

**Comment by phaza** [comment]
Perhaps make GEOMETRY and GEOGRAPHY into const variables, to remove the
possibility of spelling errors.
If you make a PR and don't break backwards compatibility, I'll merge it.

**Comment by hopewise** [comment]
> The geometry type has a much richer set of functions than geography, relationship checks are generally faster, and it has wider support currently across desktop and web-mapping tools.

http://gis.stackexchange.com/questions/26082/what-is-the-difference-between-geometric-and-geographic-columns

To insert a point in geomitry format:
```
\DB::statement("INSERT INTO points (latlong)
            VALUES(
            ST_SetSRID(ST_MakePoint($latitude, $longitude), 4326)
            );");

The migration:

DB::statement(DB::raw("ALTER TABLE \"".env('DB_SCHEMA', '')."\".\"points\" ADD COLUMN \"latlong\" geometry;"));

```
