### ISSUE TITLE
check for postgis extension

### ISSUE THREAD

**Issue by jubairsaidi** [mstaack/laravel-postgis#30]
Any chance this can be implemented into either the documentation or directly into the schema builder when creating postgis field types?

```
if(DB::connection('pgsql')->table("pg_extension")->where('extname','postgis')->count() === 0){
    DB::connection('pgsql')->statement('CREATE EXTENSION postgis;');
}
```

**Comment by phaza** [comment]
There is a method for it, but I removed it from th docs because creating
extensions requires super user access iirc, and in most cases the app
database use will not be a superuser.

**Comment by jubairsaidi** [comment]
ahh I see your point, though it only requires super user for that database.  Any chance you can bring it back with a note about permissions?  I for example usually have 1 database per app and never use the same database for multiple apps.  I'd have to ask around but I figure it's a pretty common practice?

**Comment by jubairsaidi** [comment]
I see your point, any chance you can add it back with a note about permissions?

**Comment by phaza** [comment]
I'd rather just have the enablePostgis method check if the current_user as permission to create extensions. Feel free to make a PR :)

**Comment by jubairsaidi** [comment]
ok will do! may take a few days to get into, but I'll be getting into it for sure.
