### ISSUE TITLE
Updating a geometry and using the save() method will not update the model

### ISSUE THREAD

**Issue by huesy** [mstaack/laravel-postgis#39]
When updating a GIS attribute directly, the original and current attributes are being updated at the same time.  This prevents the use of the `save()` method when updating an existing model.

To see in action:

``` PHP
// Original
$location = Location::find(1);
print_r($location);
// attributes::latlng = POINT(1 1)
// original::latlng   = POINT(1 1)

// Modified
$location->latlng->setLat(10);
print_r($location);
// attributes::latlng = POINT(1 10)
// original::latlng   = POINT(1 10) - Incorrect

$location->save();

// Saved
$location = Location::find(1);
print_r($location);
// attributes::latlng = POINT(1 1) - Incorrect
// original::latlng   = POINT(1 1) - Incorrect

```

The issue is that Laravel does not clone the Geometry objects when populating the original attributes array.  PHP will create a reference for the objects and therefore cause both the current and original attribute to be updated at the same time.  When `save()` is called, Laravel checks for any dirty attributes, and since it cannot find any, it cancels the DB update.

Below is a fix I've written which simply clones any attributes that are instances of GeometryInterface.

Please note that this has only been tested for the Point geometry in Laravel 5.2.

``` PHP
<?php

namespace MyPackage\LaravelPostgis\Eloquent;

use Phaza\LaravelPostgis\Geometries\GeometryInterface;

trait PostgisTrait
{

    use \Phaza\LaravelPostgis\Eloquent\PostgisTrait

    /**
     * While syncing the original attributes with the current, clone any
     * geometries to avoid any referencing.
     *
     * @access public
     * @return $this
     */
    public function syncOriginal()
    {
        foreach($this->attributes as $key => $value) {
            foreach($this->getPostgisFields() as $field => $geometry) {
                if ($value instanceof GeometryInterface) {
                    $this->original[$key] = clone $value;
                } else {
                    $this->original[$key] = $value;
                }
            }
        }

        return $this;
    }

}
```

**Comment by kaynz** [comment]
@phaza Can you have a look into this?

**Comment by oldskool73** [comment]
bump... this is pretty fundamentally broken as is, no?

**Comment by LiamKarlMitchell** [comment]
Updating a geometry and using the save() method will not update the model.

With tinker I can see that the geometry on my model "point" is not considered dirty after changing it.,

```
// Given a model exists with point in database already.
$r = Something::find(1);
$r->point->setLat(4);
$r->getDirty()
```

Does not contain 'point'.

The fix above from huesy does appear to fix it.
