### ISSUE TITLE
Can I use it with Lumen (just Lumen)?

### ISSUE THREAD

**Issue by MarquinhosPT** [mstaack/laravel-postgis#43]
Hi,

Can I use this just with lumen framework?

I add to bootstrap/app.php:
$app->register('Phaza\LaravelPostgis\DatabaseServiceProvider');

I have an error after "php artisan":

[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Phaza\LaravelPostgis\DatabaseServiceProvider' not found

Am I doing sometihing wrong?

Thanks,
PM

**Comment by xrain0610** [comment]
Do you have been to install the package successfully?

**Comment by ShaoZeMing** [comment]
我遇到的不一样，我添加了bootstrap / app.php：
 $app->register(Phaza\LaravelPostgis\DatabaseServiceProvider::class);


文件代码：
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLocationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('locations', function(Blueprint $table)
        {
            $table->bigincrements('id');
            $table->string('name');
            $table->string('mobile', 12)->comment('电话')->default(13333333333);
            // $table->string('mobile', 12)->comment('电话')->unique();
            $table->text('address')->comment('地址');
            $table->tinyInteger('status')->default(0)->comment('状态：0正常，1锁定');
            $table->point('geom')->comment('地址数据收集');
            $table->bigInteger('r_id')->comment('对应师傅表id')->default(0);
            $table->timestamps();
        });
    }



执行命令：
php artisan migrate


我获得错误：
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Database\Schema\Blueprint::point()

我也是lumen5.4*

**Comment by sirber** [comment]
In Lumen 5.8,

```
class DatabaseServiceProvider extends PostgresDatabaseServiceProvider
{
    public function boot() {
      // Load the config
      $config_path = __DIR__ . '/../config/postgis.php';
      $this->publishes([$config_path => config_path('postgis.php')], 'postgis');
      $this->mergeConfigFrom($config_path, 'postgis');
    }
```

Call to undefined function Phaza\LaravelPostgis\config_path()

**Comment by sirber** [comment]
Why closed? Was it fixed?

**Comment by mstaack** [comment]
sry, not aiming for lumen support so far

**Comment by sirber** [comment]
Thank you for the clarification!

**Comment by treehousetim** [comment]
I created this in my Lumen stack and it has resolved all problems with using this package with lumen.

https://gist.github.com/mabasic/21d13eab12462e596120
