### ISSUE TITLE
Can not change column type

### ISSUE THREAD

**Issue by butaevg** [mstaack/laravel-postgis#99]
`public function up()
    {
        Schema::table('districts', function ($table) {
            $table->multipolygon('geom')->change();
        });
    }
`

Unknown column type "multipolygon" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known typ
  es with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Typ
  e. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the
   cache or forgot some mapping information.

**Comment by chilio** [comment]
It seems that change() is not fully implemented (only addColumn) in Blueprint....:(
@njbarrett could you comment on this?
